### ISSUE TITLE
Lint the shell scripts

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/deploy#80]
> [Shellcheck](https://www.shellcheck.net/) finds bugs in your shell scripts.

Add linting via Shellcheck to ensure that we follow best practices with these shell scripts, and clean up existing violations. The easiest way is probably via the [Shellcheck GitHub Action](https://github.com/marketplace/actions/shellcheck), plus some documentation.

**Comment by bickelj** [comment]
This has been happening and works great.
