### ISSUE TITLE
Upgrade Keycloak

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/deploy#95]
The Keycloak major version is currently 22 while we have 20 deployed. When moving Keycloak to another machine #94, upgrade it, make sure it works with the extension libraries (https://github.com/PhilanthropyDataCommons/auth/issues/27).

**Comment by bickelj** [comment]
We have a separate machine with Keycloak installed but it needs some work:
* Debian 11.7 is installed
* There is no associated test machine
* It has an old Keycloak as well
* It does not have the PDC Keycloak extensions

A possible plan is this:
1. Take a snapshot of that machine
2. Create an associated test machine from that snapshot
3. Do the upgrade in test
4. Do the upgrade in prod
5. Do steps 1-4 for the db as well

However, that machine also has a database associated, also with an old version of Postgresql. So there is more to it. But it still may be worthwhile to do the clone of the database, etc., as well.

Since this machine is currently unused, it would be faster to reverse some of the steps:
1. Do the upgrades in prod (unused prod)
2. Clone/fork the machine and DB in prod.

**Comment by bickelj** [comment]
I upgraded the DB to Postgres 15 and the underlying machine to Debian 12 bookworm. And after upgrading, all seems OK with Keycloak (e.g. I can log in successfully to the admin interface and poke around with no errors, indicating `nginx`, `openjdk`, `keycloak`, etc., all work).

**Comment by bickelj** [comment]
The above work was done under the assumption that we were going to unify Keycloak instances. However, that is not the case. [PDC still needs its own separate instance](https://chat.opentechstrategies.com/#narrow/stream/37-Infra/topic/keycloak/near/172379), which has yet to be upgraded.

**Comment by bickelj** [comment]
We upgraded but need another upgrade. Keeping it open until that's complete.

**Comment by slifty** [comment]
@bickelj the issue *body* is specific about a particular version (title should too to be honest) -- could you document what version we've upgraded to and what version you want us to upgrade to?

**Comment by bickelj** [comment]
We are on a 22 version, need to be on a 23 version, currently 23.0.5.

**Comment by bickelj** [comment]
Upgrade to 23.0.5 complete.
